### PR TITLE
Seamless integration of Tailwindcss in the codebase

### PR DESCRIPTION
**Pull request by yashthipsay**
Link T-14
1. Proper and seamless integration of tailwindcss into the code base.
2. Added a TailwindCSS.swelte file for integration of css.
3. Proper documentation of changes and explanation regarding the same.
4. Working correctly with npx vite build
5. Very few css components have been kept the same such as box shadow property, that would not work with tailwindcss.
6. Changes commented

Final result:
Screenshot 2023-09-26 185922

### CODE REVIEW

**Comment by yashthipsay** [comment]
Hi @timscodebase, please clear the cache in Vercel and redeploy the project. The background color does not seam to appear on deployment

***Edit*** - Problem solved

**Comment by timscodebase** [comment]
@yashthipsay THANK YOU!

**Comment by yashthipsay** [comment]
#

> @yashthipsay THANK YOU!

Thank you for the opportunity @timscodebase!

**Comment by yashthipsay** [comment]
Hi @timscodebase 
Will this PR be accepted for hacktoberfest2023? Would appreciate your response.

**Comment by timscodebase** [comment]
I doubt it. Sorry. I am not happyThanks,Tim SmithOn Sep 27, 2023, at 20:02, Yash T ***@***.***> wrote:﻿
Hi @timscodebase
Will this PR be accepted for hacktoberfest2023? Would appreciate your response.

**Pull request merged**
